### PR TITLE
Update to Halide 10.0.0

### PR DESCRIPTION
**Pull request by OPNA2608**
Closes https://github.com/timothybrooks/hdr-plus/issues/69

WFM:tm:, though I know bugger-all about this project's codebase so if any of that won't fly then please lmk.

### CODE REVIEW

**Comment by OPNA2608** [comment]
CI passing now, albeit not *super* pretty. Built & tested locally on x86_64 and aarch64 Linux.

**Comment by OPNA2608** [comment]
I've squashed it down to 2 commits. The first one updates everything to be compatible with Halide 10.0.0's changes, the second one pins the CI to use Halide 10.0.0 instead of the latest commit from master to fix the following build error that I don't quite get.

> [ 39%] Generating align_and_merge.runtime.o
> Scanning dependencies of target align_and_merge.update
> [ 42%] Generating align_and_merge.h, align_and_merge.o
> Unhandled exception: Error: All Params and embedded Buffers must have unique names, but the name 'gauss_down4_kernel' was seen multiple times.
> 
> make[2]: *** [align_and_merge.h] Error 255

**Comment by TalKlinger** [comment]
Is it going to be merged?

**Comment by Titaniumtown** [comment]
Does this work, should I merge it?

**Comment by OPNA2608** [comment]
We were using the first patch patch + Halide 10.0.0 as dependencies for our megapixels package in Nixpkgs and everything seemed to work as well as it could. hdr-plus support has since been dropped from the project and I haven't done any extensive testing with it, but our hdr-plus package with this patch + Halide 10.0.0 still builds as of [2021-05-07](https://hydra.nixos.org/build/142619809).

**Pull request merged**
