### PR TITLE
Add build actions for push event

### PR DESCRIPTION
**Pull request by brotherofken**
Add basic CI based on [GitHub Actions](https://help.github.com/en/actions) to check if the build succeeds with new changes.

There are two steps:
1. Build Halide from Source;
2. Build hdrplus and stack_frames binaries.

Here is an example of this PR that finished sucessfully: https://github.com/brotherofken/hdr-plus/pull/1

### CODE REVIEW

**Comment by Titaniumtown** [comment]
Where would the status of the current build be displayed? (Sorry if this is a stupid question, as I do not know much about Github Actions)

**Comment by brotherofken** [comment]
I think that build status is not displayed because this branch belongs to another repository.
However, you can find it here: https://github.com/brotherofken/hdr-plus/pull/1

**Comment by Titaniumtown** [comment]
Oh ok, sorry. I guess I didn't see the part when you mention the example.
It looks all good to me!

**Comment by brotherofken** [comment]
Cool, thank! It just launched: https://github.com/timothybrooks/hdr-plus/runs/491214892

**Comment by Titaniumtown** [comment]
Looks good!

**Comment by brotherofken** [comment]
One side note for the future. Could you do "squash and merge" pull requests to make history in the  master cleaner?
It's described on the following page: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits

**Comment by Titaniumtown** [comment]
Thanks, I didn't know about that. I will do that moving forward!

**Comment by brotherofken** [comment]
Thanks! :+1:

**Pull request merged**
