### PR TITLE
fix merge weight compuation bug

### PR DESCRIPTION
**Pull request by gooooloo**
By the comment of `max_dist`, I believe here should have a `/factor` .

### CODE REVIEW

**Comment by timothybrooks** [comment]
You are right--thanks for noticing this. Do the current factor and other relevant tuning (mins and maxes) still produce visually pleasing results with these changes? They were initially set with the typo, and may need to be adjusted once the typo is corrected. Have you tried processing any images with this change? If you need some, I could send you raw images to test with.

**Comment by Titaniumtown** [comment]
Bump! Do you know what the effect is of the change? Could you provide images processed though this code and your modified one? What are the advantages?

Looking forward to your response,
Titaniumtown

**Comment by gooooloo** [comment]
sorry I dont have time ( and interest ) on this issue any more. So I am afraid you have to test it by yourself @Titaniumtown
I am fine if you just close this pull request directly. @timothybrooks

**Comment by Titaniumtown** [comment]
I am closing this then.

**Pull request closed without merging**
