### PR TITLE
(WIP) fixes workflow and adds some stuff

### PR DESCRIPTION
**Pull request by Titaniumtown**
btw, i'm sorry there is so many commits, lol. I was figuring out how to use github actions.

What this PR does:
- ubuntu x86 and arm support (both 32-bit and 64-bit)
- fixes llvm version issues

What needs to be fixed:
- fix issues w/ build_all and build_halide: https://github.com/Titaniumtown/hdr-plus/actions/runs/99436927

Things that could be implemented:
- osx support (I tried but it didn't work)

### CODE REVIEW

**Comment by Titaniumtown** [comment]
oh btw the checks will probably fail atm bc I got to fix some more stuff.

**Comment by Titaniumtown** [comment]
@brotherofken do you have any suggestions? I believe you have more experience at this than me.

**Comment by brotherofken** [comment]
Looks good to me. Became a bit complicated though.
Do you think that anyone will try to run this on a 32-bit arch and especially arm32? :-)

**Comment by Titaniumtown** [comment]
No, but it doesn't really hurt to have it. And in the rare case someone will try to compile on a 32-bit system, it'll be useful.

**Comment by Titaniumtown** [comment]
@brotherofken , see the issue i'm having: https://github.com/timothybrooks/hdr-plus/actions/runs/99488199

**Comment by Titaniumtown** [comment]
Did I do something wrong?

**Comment by Titaniumtown** [comment]
I think I found the issue...

**Comment by Titaniumtown** [comment]
wait no I haven't, I still need help. lol

**Comment by Titaniumtown** [comment]
oh! it seemed like it built! https://github.com/Titaniumtown/hdr-plus/runs/657698910?check_suite_focus=true

**Comment by Titaniumtown** [comment]
So I do know what I'm doing.

**Comment by Titaniumtown** [comment]
@brotherofken does everything look good to you? I need to be 100% sure before I merge.

**Comment by brotherofken** [comment]
Regarding the last failure. Could you check if this project has enough free storage?

It should be somewhere in settings -> billing -> storage

**Comment by Titaniumtown** [comment]
I don't think I have access to that. Correct me if I'm wrong.

**Comment by Titaniumtown** [comment]
I just removed the part about updating the packages.

**Pull request merged**
