### PR TITLE
(WIP) fix workflow errors w/ halide build

### PR DESCRIPTION
**Pull request by Titaniumtown**
Getting build errors for halide, this is the PR relating to that.

### CODE REVIEW

**Comment by Titaniumtown** [comment]
How do you set the github to use clang and not gcc?? I can't figure it out

**Comment by Titaniumtown** [comment]
omg, I can't figure it out. any help would be appreciated. I am new to github actions.

**Comment by Titaniumtown** [comment]
oh, I figured it out.

**Comment by Titaniumtown** [comment]
I'm just going to move this to my own fork, then make a pull request from there.

**Comment by brotherofken** [comment]
I don't like the message:
```CMake Error at CMakeLists.txt:168 (message):
  LLVM version must be 9.0 or newer
```
Build bot has LLVM 8.0, so we need to figure out how to update LLVM.

**Comment by Titaniumtown** [comment]
Yea, i'm working on it on my fork. I'll submit a pull request shortly

**Pull request closed without merging**
